sonar.organization=noirlang
sonar.projectKey=noirlang_worm
sonar.projectName=Worm
sonar.projectVersion=1.0

# Paths to source directories
sonar.sources=src,ui

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Exclude files that do not need code quality checks
sonar.exclusions=tests/**/*,dist/**/*,target/**/*,packaging/**/*,scripts/**/*
