#!/usr/bin/env python3
"""Generate CONTRIBUTORS.md from git history."""

from __future__ import annotations

import re
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "CONTRIBUTORS.md"
LINE_RE = re.compile(r"^\s*(\d+)\s+(.+?)\s+<([^>]+)>$")


def run_git_shortlog() -> list[tuple[int, str, str]]:
    result = subprocess.run(
        ["git", "shortlog", "-sne", "--all"],
        cwd=ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    contributors: list[tuple[int, str, str]] = []
    for line in result.stdout.splitlines():
        match = LINE_RE.match(line)
        if not match:
            continue
        commits, name, email = match.groups()
        contributors.append((int(commits), name.strip(), email.strip()))
    return contributors


def escape_cell(value: str) -> str:
    return value.replace("|", "\\|")


def render(contributors: list[tuple[int, str, str]]) -> str:
    total_commits = sum(commits for commits, _, _ in contributors)
    total_people = len(contributors)
    rows = "\n".join(
        f"| {commits} | {escape_cell(name)} | `{escape_cell(email)}` |"
        for commits, name, email in contributors
    )
    if not rows:
        rows = "| 0 | - | - |"

    return f"""# Contributors

<!--
Generated by scripts/update_contributors.py.
Do not edit the table manually; run the script after contributor history changes.
-->

This file is generated from the repository git history with:

```bash
python3 scripts/update_contributors.py
```

Total contributors: **{total_people}**  
Total commits counted: **{total_commits}**

| Commits | Contributor | Email |
| ---: | --- | --- |
{rows}
"""


def main() -> None:
    OUTPUT.write_text(render(run_git_shortlog()), encoding="utf-8")


if __name__ == "__main__":
    main()
